# This is a basic workflow to help you get started with Actions

name: merge-with-master

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-release:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: install packages
      run: |
        echo "${{ secrets.NPM_REGISTRY }}" > ~/.npmrc
        echo "${{ secrets.NPM_TOKEN }}" >> ~/.npmrc
        yarn install
        yarn build
        yarn test
        yarn release -- --yes
        git checkout develop
        git pull -u origin master
        git push -u origin develop
