# This is a basic workflow to help you get started with Actions

name: merge-with-master

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-release:
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: prepare
      run: |
        echo "${{ secrets.NPM_REGISTRY }}" > ~/.npmrc
        echo "${{ secrets.NPM_TOKEN }}" >> ~/.npmrc
        yarn install
    - name: build-and-test
      run: |
        yarn build
        yarn test
    - name: publish-packages
      run: |
        yarn publish-packages --yes
    - name: Send mailer
      uses: devellany/send-mail@v1.0.2
      with:
          host: ${{secrets.MAIL_HOST}}
          port: 578
          account: ${{secrets.MAIL_ACCOUNT}}
          password: ${{secrets.MAIL_PASSWORD}}
          sender: ${{secrets.MAIL_SENDER}}
          from: ${{secrets.MAIL_SENDER}}
          to: ${{secrets.MAIL_TO}}
          subject: CI/CD STATUS
          body: your messages.
          # Optional content type (defaults to text/plain)
          contentType: text/plain
          # Optional attachment files (JSON type. require property 'path')
          attachments: '[{"path":"README.md"}]'
